---
- hosts: local
  become: true
  vars_files:
    - secrets.yml  # Include the secrets file for sensitive information

  tasks:
    # Task 1: Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Task 2: Install Docker Compose
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    # Task 3: Create Traefik directory
    - name: Create Traefik directory
      file:
        path: "/home/{{ lookup('env', 'USER') }}/autocert"  # Use the environment variable to get the username
        state: directory
        mode: '0755'

    # Task 4: Copy docker-compose.yml template to the host
    - name: Copy docker-compose.yml template
      template:
        src: ./docker-compose-template.yml.j2
        dest: "/home/{{ lookup('env', 'USER') }}/autocert/docker-compose.yml"
        mode: '0644'

    # Task 5: Copy traefik.yml to the host
    - name: Copy traefik.yml
      copy:
        src: ./traefik.yml
        dest: "/home/{{ lookup('env', 'USER') }}/autocert/traefik.yml"
        mode: '0644'

    # Task 6: Create acme.json with correct permissions
    - name: Create acme.json with correct permissions
      file:
        path: "/home/{{ lookup('env', 'USER') }}/autocert/acme.json"
        state: touch
        mode: '0600'

    # Task 7: Start Traefik with Docker Compose
    - name: Start Traefik
      command: docker-compose up -d
      args:
        chdir: "/home/{{ lookup('env', 'USER') }}/autocert"
